### ISSUE TITLE
Kata console error should be handled properly

### ISSUE THREAD

**Issue by girikuncoro** [kata-ai/kata-cli#32]
Similar to #27, kata console error should be handled properly when cannot find bot.yml. Executing `kata console` outside bot directory or directory inside (i.e. flows) give error tracing:
```
$ kata console
[ERROR] kata-cli/undefined 2017-12-06 18:51:27 : { Error: ENOENT: no such file or directory, open './bot.yml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Helper.loadYaml (/usr/local/lib/node_modules/kata-cli/lib/components/scripts/helper.js:40:33)
    at Bot.console (/usr/local/lib/node_modules/kata-cli/lib/components/bots/bot.js:338:37)
    at Command.args (/usr/local/lib/node_modules/kata-cli/lib/components/main.js:93:17)
    at Command.listener (/usr/local/lib/node_modules/kata-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/kata-cli/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/kata-cli/node_modules/commander/index.js:475:21)
    at Main.<anonymous> (/usr/local/lib/node_modules/kata-cli/lib/components/main.js:24:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/kata-cli/lib/components/main.js:4:58)
    at <anonymous> errno: -2, code: 'ENOENT', syscall: 'open', path: './bot.yml' }
```

**Comment by aliarham11** [comment]
Done in PR https://github.com/kata-ai/kata-cli/pull/38
